CREATE TABLE artist (
    artist_id BIGSERIAL NOT NULL PRIMARY KEY,
    artist_name VARCHAR(100),
    album_id INTEGER,
    review_id INTEGER,
    alias VARCHAR(100),
    small_biography TEXT
);

INSERT INTO artist (artist_name, album_id, review_id, alias, small_biography) VALUES
    ('Aretha Franklin', random(), random(), 'Queen of Soul', 'Legendary singer known for her powerful voice.'),
    ('Chuck Berry', random(), random(), 'Father of Rock and Roll', 'Pioneer of rock music and iconic guitarist.'),
    ('Michael Jackson', random(), random(), 'King of Pop', 'Global pop sensation and innovative entertainer.'),
    ('Bill Haley & His Comets', random(), random(), 'Rock and Roll Trailblazers', 'Early rock and roll pioneers.'),
    ('Led Zeppelin', random(), random(), 'Legendary Rock Band', 'Known for their iconic rock anthems.'),
    ('The Kingsmen', random(), random(), 'Garage Rock Pioneers', 'Famous for the hit song  Louie Louie .'),
    ('Marvin Gaye', random(), random(), 'Prince of Soul', 'Smooth and soulful vocalist with social consciousness.'),
    ('The Rolling Stones', random(), random(), 'Rock Legends', 'Long-standing rock band with numerous hits.'),
    ('Elvis Presley', random(), random(), 'King of Rock and Roll', 'Iconic figure in the history of rock music.'),
    ('Bob Dylan', random(), random(), 'Voice of a Generation', 'Nobel Prize-winning singer-songwriter.'),
    ('The Beatles', random(), random(), 'Fab Four', 'Revolutionized music and pop culture.'),
    ('The Beach Boys', random(), random(), 'Harmony Masters', 'Influential for their vocal harmonies and beach-themed music.'),
    ('Little Richard', random(), random(), 'Architect of Rock and Roll', 'Energetic and flamboyant rock and roll pioneer.'),
    ('Ray Charles', random(), random(), 'Genius of Soul', 'Blind pianist and soulful singer.'),
    ('Eagles', random(), random(), 'Rock Superstars', 'Famous for their harmonious sound and hit songs.'),
    ('The Righteous Brothers', random(), random(), 'Blue-Eyed Soul', 'Known for the emotional ballad  Youve Lost That Lovin Feelin'),
    ('The Temptations', random(), random(), 'Motown Legends', 'Smooth vocal group with soulful hits.'),
    ('John Lennon', random(), random(), 'Imagine', 'Co-founder of The Beatles and influential solo artist.'),
    ('Nirvana', random(), random(), 'Grunge Pioneers', 'Led by Kurt Cobain, influential in the grunge movement.'),
    ('Bruce Springsteen', random(), random(), 'The Boss', 'Energetic rock performer and songwriter.'),
    ('The Doors', random(), random(), 'Psychedelic Rock', 'Known for their poetic lyrics and unique sound.'),
    ('Stevie Wonder', random(), random(), 'Musical Prodigy', 'Blind since birth, multi-instrumentalist and soulful singer.'),
    ('Derek and the Dominos (Eric Clapton)', random(), random(), 'Blues-Rock Supergroup', 'Led by Eric Clapton, famous for Layla .'),
    ('Queen', random(), random(), 'Champions', 'Legendary rock band with diverse musical styles.'),
    ('Eddie Cochran', random(), random(), 'Rockabilly Star', 'Influential rock and roll and rockabilly artist.'),
    ('The Kinks', random(), random(), 'British Invasion', 'Known for their distinctive sound and witty lyrics.'),
    ('Simon & Garfunkel', random(), random(), 'Folk Rock Duo', 'Harmonious duo with poetic and introspective songs.'),
    ('Al Green', random(), random(), 'The Reverend', 'Smooth soul singer and ordained pastor.'),
    ('Jimi Hendrix', random(), random(), 'Guitar Virtuoso', 'Innovative guitarist and rock icon.'),
    ('Jerry Lee Lewis', random(), random(), 'The Killer', 'Energetic and flamboyant rock and roll pioneer.'),
    ('Buddy Holly', random(), random(), 'Rockabilly Legend', 'Influential figure in the early days of rock and roll.'),
    ('The Police', random(), random(), 'New Wave Icons', 'Sting-led band with a blend of rock and new wave.'),
    ('OutKast', random(), random(), 'Hip-Hop Duo', 'Andre 3000 and Big Boi, known for their genre-blending music.'),
    ('Bo Diddley', random(), random(), 'Bo Diddley Beat', 'Innovative guitarist and rhythm pioneer.'),
    ('James Brown', random(), random(), 'Godfather of Soul', 'The hardest-working man in show business.'),
    ('Prince', random(), random(), 'Purple One', 'Musical genius and innovative artist.'),
    ('The Who', random(), random(), 'Rock Legends', 'Known for their energetic performances and concept albums.'),
    ('R.E.M.', random(), random(), 'Alternative Pioneers', 'Influential in the alternative rock genre.'),
    ('Cream', random(), random(), 'Supergroup', 'Eric Clapton, Ginger Baker, and Jack Bruce in a rock supergroup.'),
    ('U2', random(), random(), 'Irish Rock Icons', 'Led by Bono, known for their anthemic rock songs.'),
    ('Sam Cooke', random(), random(), 'Soulful Crooner', 'One of the greatest soul and R&B singers.'),
    ('Grandmaster Flash and the Furious Five', random(), random(), 'Hip-Hop Pioneers', 'Influential in the early days of hip-hop.'),
    ('Wilson Pickett', random(), random(), 'Wicked Pickett', 'Soulful singer known for his powerful voice.'),
    ('The Byrds', random(), random(), 'Folk Rock Pioneers', 'Known for blending folk and rock elements.'),
    ('Creedence Clearwater Revival', random(), random(), 'Swamp Rock', 'Led by John Fogerty, known for their swamp rock sound.'),
    ('Big Joe Turner', random(), random(), 'Boss of the Blues', 'Blues and R&B singer with a powerful voice.'),
    ('Aerosmith', random(), random(), 'Bad Boys from Boston', 'Hard rock band with a string of hits.'),
    ('Rod Stewart', random(), random(), 'Rod the Mod', 'Versatile rocker with a raspy voice.'),
    ('Don McLean', random(), random(), 'American Pie', 'Folk singer-songwriter known for the iconic song.'),
    ('Otis Redding', random(), random(), 'King of Soul', 'Influential soul singer with a raw emotive style.'),
    ('Bee Gees', random(), random(), 'Disco Legends', 'Famous for their contributions to the disco era.'),
    ('Lynyrd Skynyrd', random(), random(), 'Southern Rock Pioneers', 'Known for  Free Bird  and  Sweet Home Alabama .'),
    ('Dr. Dre', random(), random(), 'Hip-Hop Mogul', 'Legendary rapper, producer,'),
	('Percy Sledge', random(), random(), 'Soulful Balladeer', 'Known for the classic  When a Man Loves a Woman .'),
    ('Ben E. King', random(), random(), 'Stand By Me', 'R&B and soul singer, famous for the timeless hit  Stand By Me .'),
    ('Gloria Gaynor', random(), random(), 'Queen of Disco', 'Iconic disco singer, best known for  I Will Survive .'),
    ('Rick James', random(), random(), 'Super Freak', 'Funky and flamboyant artist, famous for  Super Freak .'),
    ('Procol Harum', random(), random(), 'Progressive Rock', 'Known for the classic  A Whiter Shade of Pale .'),
    ('The Ronettes', random(), random(), 'Girl Group', 'Legendary girl group, famous for  Be My Baby .'),
    ('Fleetwood Mac', random(), random(), 'Rock Legends', 'British-American rock band with a string of hits.'),
    ('The Animals', random(), random(), 'British Invasion', 'Rock band known for hits like  House of the Rising Sun .'),
    ('The Supremes', random(), random(), 'Motown Royalty', 'One of Motowns most successful acts with numerous chart-topping hits.'),
    ('Sugarhill Gang', random(), random(), 'Hip-Hop Pioneers', 'Early hip-hop group known for the groundbreaking  Rappers Delight .'),
    ('The Jackson 5', random(), random(), 'Motown Sensation', 'Childhood group of Michael Jackson, known for hits like  I Want You Back .'),
    ('Joan Jett & The Blackhearts', random(), random(), 'Rock Goddess', 'Punk rock and rock artist, famous for  I Love Rock N Roll .'),
    ('The Human League', random(), random(), 'Synth-Pop Pioneers', 'Electropop band known for hits like  Dont You Want Me .'),
    ('Pearl Jam', random(), random(), 'Grunge Icons', 'Influential grunge band with hits like  Jeremy  and  Alive .'),
    ('Madonna', random(), random(), 'Queen of Pop', 'Iconic pop singer, actress, and cultural influencer.'),
    ('Guns N  Roses', random(), random(), 'Rock Icons', 'Hard rock band with hits like  Sweet Child O Mine  and  November Rain .'),
    ('Red Hot Chili Peppers', random(), random(), 'Funky Rockers', 'Alternative rock band with a fusion of funk and rock elements.'),
    ('Elton John', random(), random(), 'Rocket Man', 'Legendary singer-songwriter and pianist with a vast catalog of hits.'),
    ('ABBA', random(), random(), 'Swedish Pop Sensation', 'One of the most successful pop groups in history, known for  Dancing Queen .'),
    ('Journey', random(), random(), 'Arena Rock Legends', 'Rock band with anthemic hits like  Dont Stop Believin.'),
    ('Sam & Dave', random(), random(), 'Soul Duo', 'Soulful duo known for hits like  Soul Man  and  Hold On, Im Comin .'),
    ('AC/DC', random(), random(), 'Rock or Bust', 'Legendary rock band known for their electrifying performances.'),
    ('The Everly Brothers', random(), random(), 'Harmony Kings', 'Influential duo known for their close harmonies and rockabilly sound.'),
    ('The Penguins', random(), random(), 'Doo-Wop Legends', 'Doo-wop group famous for the classic  Earth Angel .'),
    ('Patsy Cline', random(), random(), 'Queen of Country', 'Country music icon known for her timeless songs and emotional performances.');
