CREATE TABLE IF NOT EXISTS genre (
    genre_id BIGSERIAL PRIMARY KEY NOT NULL,
    genre_name VARCHAR(50) NOT NULL,
    genre_image_url VARCHAR(255)
);

-- Insert data for genres
INSERT INTO
    genre (genre_name, genre_image_url)
VALUES
    (
        'Rock',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Pop',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'R&B',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Hip-Hop',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Country',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Jazz',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Blues',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Electronic',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Reggae',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Classical',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Rap',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Trap',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Soul',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Folk',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Indie',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Metal',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Punk',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Alternative',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'K-Pop',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    ),
    (
        'Latin',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Pieter_Bruegel_d._%C3%84._014.jpg/440px-Pieter_Bruegel_d._%C3%84._014.jpg'
    );